# docker-compose.yml

services:
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis/redis-stack:7.2.0-v17
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - "6379:6379" # Redis server
      - "8001:8001" # RedisInsight UI
    volumes:
      - redis-stack-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  rabbitmq-data:
  rabbitmq-logs:
  redis-stack-data:
