services:
  eureka-server:
    image: steeltoeoss/eureka-server:latest
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_PORT=8761
      - EUREKA_SERVER_HOST=0.0.0.0
      - EUREKA_SERVER_DEFAULT_ZONE=default
      - EUREKA_SERVER_DEFAULT_REGION=default
      - EUREKA_SERVER_DEFAULT_GROUP=default
      - EUREKA_SERVER_DEFAULT_APPLICATION=default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - prediction-service-network

  # Prediction Service
  prediction-service:
    image: hzeroxium/prediction-service:latest
    container_name: prediction-service
    restart: unless-stopped
    ports:
      - "8001:8000" # FastAPI API
    depends_on:
      - eureka-server
    env_file:
      - .env

    networks:
      - prediction-service-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  prediction-service-network:
    driver: bridge
